# Generated by Django 3.2.6 on 2022-08-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_alter_category_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='updated_date',
        ),
    ]
