# Generated by Django 3.2.6 on 2022-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_auto_20220806_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=300, verbose_name='question title'),
        ),
    ]
